services:
  gromnie-proxy:
    build:
      context: .
      dockerfile: crates/gromnie-proxy/Dockerfile
      args:
        - GIT_SHA
    ports:
      - "8081:8081"
    env_file:
      - crates/gromnie-web/.env
    environment:
      - GROMNIE_LISTEN=0.0.0.0:8081
      - AUTH_ENABLE=false

  gromnie-web:
    build:
      context: .
      dockerfile: crates/gromnie-web/Dockerfile
      args:
        - GIT_SHA
    ports:
      - "8080:8080"
    environment:
      - WISP_HOST=localhost:8081
    depends_on:
      - gromnie-proxy
