services:
  gromnie-proxy:
    build:
      context: .
      dockerfile: crates/gromnie-proxy/Dockerfile
      args:
        - GIT_SHA
    ports:
      - "8081:8081"
    environment:
      - GROMNIE_LISTEN=0.0.0.0:8081

  gromnie-web:
    build:
      context: .
      dockerfile: crates/gromnie-web/Dockerfile
      args:
        - GIT_SHA
    ports:
      - "8080:8080"
    environment:
      - PROXY_SCHEME=http
      - PROXY_UPSTREAM=gromnie-proxy:8081
    depends_on:
      - gromnie-proxy
