use anyhow::{Context, Result};
use std::any::Any;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::{Duration, SystemTime};
use tracing::warn;
use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiView};

use crate::Script as HostScript;
use crate::{EventFilter, context::ScriptContext};
use gromnie_events::{
    ClientEvent, ClientStateEvent, ClientSystemEvent, GameEventMsg, ProtocolEvent, S2CEvent,
    SimpleGameEvent as GameEvent,
};

// Generate bindings from WIT (use the canonical definition from gromnie-scripting-api)
wasmtime::component::bindgen!({
    path: "../gromnie-scripting-api/src/wit",
    world: "script",
    imports: {
        default: async,
    },
    exports: {
        default: async,
    },
});

/// State held in the WASM store
pub struct WasmScriptState {
    /// WASI context for filesystem/stdio access
    wasi: WasiCtx,
    /// Resource table for WASI
    table: ResourceTable,
    /// Current host context, set for the duration of each callback.
    pub(crate) host_context: Option<Arc<ScriptContext>>,
    /// Script ID (for logging)
    pub(crate) script_id: String,
}

impl WasiView for WasmScriptState {
    fn ctx(&mut self) -> wasmtime_wasi::WasiCtxView<'_> {
        wasmtime_wasi::WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// Wrapper that adapts a WASM component to implement the Script trait
pub struct WasmScript {
    /// Store holds WASM instance + state
    store: Store<WasmScriptState>,
    /// WASM component instance (generated by bindgen)
    script: Script,

    /// Cached metadata (retrieved once at load time)
    id: String,
    name: String,
    description: String,
    subscribed_events: Vec<EventFilter>,

    /// File path for hot reload tracking
    file_path: PathBuf,
    /// File modification time for change detection
    modified_time: SystemTime,
}

impl WasmScript {
    /// Load a WASM component from a file
    pub async fn from_file(engine: &Engine, path: impl AsRef<std::path::Path>) -> Result<Self> {
        let path = path.as_ref();

        // Get file metadata for hot reload tracking
        let metadata = std::fs::metadata(path)
            .with_context(|| format!("Failed to read file metadata: {}", path.display()))?;
        let modified_time = metadata
            .modified()
            .with_context(|| format!("Failed to get modification time: {}", path.display()))?;

        // Load component from file
        let component = Component::from_file(engine, path)
            .with_context(|| format!("Failed to load WASM component: {}", path.display()))?;

        // Create WASI context
        let wasi = super::engine::create_wasi_context()?;
        let table = ResourceTable::new();

        let state = WasmScriptState {
            wasi,
            table,
            host_context: None,
            script_id: String::new(), // Will be updated after instantiation
        };

        let mut store = Store::new(engine, state);

        // Create linker and add WASI + host imports
        let mut linker = Linker::new(engine);

        // Add WASI support
        wasmtime_wasi::p2::add_to_linker_async(&mut linker)
            .context("Failed to add WASI to linker")?;

        // Add our host imports (will be implemented separately)
        crate::wasm::bindings::add_host_imports(&mut linker)?;

        // Instantiate the component (async)
        let script = Script::instantiate_async(&mut store, &component, &linker)
            .await
            .context("Failed to instantiate WASM script")?;

        // Call metadata functions to cache values
        let guest = script.gromnie_scripting_guest();

        // Initialize the script first
        guest
            .call_init(&mut store)
            .await
            .context("Failed to initialize script")?;

        let id = guest
            .call_get_id(&mut store)
            .await
            .context("Failed to get script ID")?;

        // Update the script_id in the store state now that we have it
        store.data_mut().script_id = id.clone();

        let name = guest
            .call_get_name(&mut store)
            .await
            .context("Failed to get script name")?;

        let description = guest
            .call_get_description(&mut store)
            .await
            .context("Failed to get script description")?;

        let subscribed_event_ids = guest
            .call_subscribed_events(&mut store)
            .await
            .context("Failed to get subscribed events")?;

        // Convert u32 discriminants to EventFilter enum
        let subscribed_events = subscribed_event_ids
            .into_iter()
            .filter_map(EventFilter::from_discriminant)
            .collect();

        Ok(Self {
            store,
            script,
            id,
            name,
            description,
            subscribed_events,
            file_path: path.to_path_buf(),
            modified_time,
        })
    }

    /// Set the host context for the current operation.
    fn set_context(&mut self, ctx: Arc<ScriptContext>) {
        self.store.data_mut().host_context = Some(ctx);
    }

    /// Clear the host context.
    fn clear_context(&mut self) {
        self.store.data_mut().host_context = None;
    }
}

impl HostScript for WasmScript {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn description(&self) -> &str {
        &self.description
    }

    fn on_load<'a>(
        &'a mut self,
        ctx: Arc<ScriptContext>,
    ) -> ::core::pin::Pin<Box<dyn ::core::future::Future<Output = ()> + ::core::marker::Send + 'a>>
    {
        self.set_context(ctx);
        Box::pin(async move {
            let guest = self.script.gromnie_scripting_guest();
            let result = guest.call_on_load(&mut self.store).await;
            self.clear_context();
            if let Err(err) = result {
                warn!(
                    target: "scripting",
                    "Script {} ({}) on_load failed: {:#}",
                    self.name,
                    self.id,
                    err
                );
            }
        })
    }

    fn on_unload<'a>(
        &'a mut self,
        ctx: Arc<ScriptContext>,
    ) -> ::core::pin::Pin<Box<dyn ::core::future::Future<Output = ()> + ::core::marker::Send + 'a>>
    {
        self.set_context(ctx);
        Box::pin(async move {
            let guest = self.script.gromnie_scripting_guest();
            let result = guest.call_on_unload(&mut self.store).await;
            self.clear_context();
            if let Err(err) = result {
                warn!(
                    target: "scripting",
                    "Script {} ({}) on_unload failed: {:#}",
                    self.name,
                    self.id,
                    err
                );
            }
        })
    }

    fn subscribed_events(&self) -> &[EventFilter] {
        &self.subscribed_events
    }

    fn on_event<'a>(
        &'a mut self,
        event: &'a ClientEvent,
        ctx: Arc<ScriptContext>,
    ) -> ::core::pin::Pin<Box<dyn ::core::future::Future<Output = ()> + ::core::marker::Send + 'a>>
    {
        let wasm_event = client_event_to_wasm(event);
        self.set_context(ctx);
        Box::pin(async move {
            let guest = self.script.gromnie_scripting_guest();
            let result = guest.call_on_event(&mut self.store, &wasm_event).await;
            self.clear_context();
            if let Err(err) = result {
                warn!(
                    target: "scripting",
                    "Script {} ({}) on_event failed: {:#}",
                    self.name,
                    self.id,
                    err
                );
            }
        })
    }

    fn on_tick<'a>(
        &'a mut self,
        ctx: Arc<ScriptContext>,
        delta: Duration,
    ) -> ::core::pin::Pin<Box<dyn ::core::future::Future<Output = ()> + ::core::marker::Send + 'a>>
    {
        let delta_millis = delta.as_millis() as u64;
        self.set_context(ctx);
        Box::pin(async move {
            let guest = self.script.gromnie_scripting_guest();
            let result = guest.call_on_tick(&mut self.store, delta_millis).await;
            self.clear_context();
            if let Err(err) = result {
                warn!(
                    target: "scripting",
                    "Script {} ({}) on_tick failed: {:#}",
                    self.name,
                    self.id,
                    err
                );
            }
        })
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }
}

impl WasmScript {
    /// Get the file path for this script
    pub fn file_path(&self) -> &PathBuf {
        &self.file_path
    }

    /// Get the modification time for this script
    pub fn modified_time(&self) -> SystemTime {
        self.modified_time
    }
}

/// Convert Rust ClientEvent to WIT ScriptEvent
fn client_event_to_wasm(event: &ClientEvent) -> gromnie::scripting::host::ScriptEvent {
    use gromnie::scripting::host::ScriptEvent as WitScriptEvent;

    match event {
        ClientEvent::Game(game_event) => WitScriptEvent::Game(game_event_to_wasm(game_event)),
        ClientEvent::Protocol(protocol_event) => WitScriptEvent::Game(
            gromnie::scripting::host::GameEvent::Protocol(protocol_event_to_wit(protocol_event)),
        ),
        ClientEvent::State(state_event) => WitScriptEvent::State(state_event_to_wasm(state_event)),
        ClientEvent::System(system_event) => {
            WitScriptEvent::System(system_event_to_wasm(system_event))
        }
    }
}

/// Convert Rust GameEvent to WIT GameEvent
fn game_event_to_wasm(event: &GameEvent) -> gromnie::scripting::host::GameEvent {
    use gromnie::scripting::host::{
        AccountData, CharacterError as WitCharacterError, CharacterIdentity, ChatMessage,
        GameEvent as WitGameEvent,
    };

    match event {
        GameEvent::CharacterListReceived {
            account,
            characters,
            num_slots,
        } => WitGameEvent::CharacterListReceived(AccountData {
            account: account.clone(),
            num_slots: *num_slots,
            characters: characters
                .iter()
                .map(|c| CharacterIdentity {
                    character_id: c.character_id.0,
                    name: c.name.clone(),
                    seconds_greyed_out: c.seconds_greyed_out,
                })
                .collect(),
        }),

        GameEvent::CharacterError {
            error_code,
            error_message,
        } => WitGameEvent::CharacterError(WitCharacterError {
            error_code: *error_code,
            error_message: error_message.clone(),
        }),

        GameEvent::ChatMessageReceived {
            message,
            message_type,
        } => WitGameEvent::ChatMessageReceived(ChatMessage {
            channel: *message_type as u8,
            message: message.clone(),
        }),

        // Handle events that still exist in GameEvent but aren't in WIT
        // These will be filtered out by the event filter in the future
        _ => {
            tracing::warn!(
                target: "scripting",
                "Received event {:?} that is not supported in WIT interface - skipping",
                event
            );
            // Return a dummy event - this should never reach WASM scripts
            // since they won't be subscribed to events not in the WIT
            WitGameEvent::ChatMessageReceived(ChatMessage {
                channel: 0,
                message: String::new(),
            })
        }
    }
}

/// Convert Rust StateEvent to WIT StateEvent
fn state_event_to_wasm(event: &ClientStateEvent) -> gromnie::scripting::host::StateEvent {
    use gromnie::scripting::host::StateEvent as WitStateEvent;

    match event {
        ClientStateEvent::Connecting => WitStateEvent::Connecting,
        ClientStateEvent::Connected => WitStateEvent::Connected,
        ClientStateEvent::ConnectingFailed { reason } => {
            WitStateEvent::ConnectingFailed(reason.clone())
        }
        ClientStateEvent::Patching => WitStateEvent::Patching,
        ClientStateEvent::Patched => WitStateEvent::Patched,
        ClientStateEvent::PatchingFailed { reason } => {
            WitStateEvent::PatchingFailed(reason.clone())
        }
        ClientStateEvent::CharacterSelect => WitStateEvent::CharacterSelect,
        ClientStateEvent::EnteringWorld => WitStateEvent::EnteringWorld,
        ClientStateEvent::InWorld => WitStateEvent::InWorld,
        ClientStateEvent::ExitingWorld => WitStateEvent::ExitingWorld,
        ClientStateEvent::CharacterError => WitStateEvent::CharacterError,
    }
}

/// Convert Rust SystemEvent to WIT SystemEvent
fn system_event_to_wasm(event: &ClientSystemEvent) -> gromnie::scripting::host::SystemEvent {
    use gromnie::scripting::host::{LoginInfo, SystemEvent as WitSystemEvent};

    match event {
        ClientSystemEvent::AuthenticationSucceeded => WitSystemEvent::AuthenticationSucceeded,
        ClientSystemEvent::AuthenticationFailed { reason } => {
            WitSystemEvent::AuthenticationFailed(reason.clone())
        }
        ClientSystemEvent::ConnectingStarted => WitSystemEvent::ConnectingStarted,
        ClientSystemEvent::ConnectingDone => WitSystemEvent::ConnectingDone,
        ClientSystemEvent::UpdatingStarted => WitSystemEvent::UpdatingStarted,
        ClientSystemEvent::UpdatingDone => WitSystemEvent::UpdatingDone,
        ClientSystemEvent::LoginSucceeded {
            character_id,
            character_name,
        } => WitSystemEvent::LoginSucceeded(LoginInfo {
            character_id: *character_id,
            character_name: character_name.clone(),
        }),
        ClientSystemEvent::Disconnected { .. } => WitSystemEvent::Disconnected,
        ClientSystemEvent::Reconnecting { .. } => WitSystemEvent::Reconnecting,
    }
}

/// Convert Rust ProtocolEvent to WIT ProtocolEvent
fn protocol_event_to_wit(event: &ProtocolEvent) -> gromnie::scripting::host::ProtocolEvent {
    use gromnie::scripting::host::{
        LoginCreatePlayerMsg, OrderedGameEvent as WitOrderedGameEvent,
        ProtocolEvent as WitProtocolEvent, S2cEvent as WitS2cEvent,
    };

    match event {
        ProtocolEvent::S2C(s2c_event) => WitProtocolEvent::S2c(s2c_event_to_wit(s2c_event)),
        ProtocolEvent::GameEvent(game_event) => WitProtocolEvent::GameEvent(WitOrderedGameEvent {
            object_id: game_event.object_id,
            sequence: game_event.sequence,
            event: game_event_msg_to_wit(&game_event.event),
        }),
        // Ignore unknown protocol events (future variants added via #[non_exhaustive])
        _ => {
            warn!(target: "scripting", "Unknown protocol event variant, skipping");
            // Return a placeholder event - this will be filtered out before reaching scripts
            WitProtocolEvent::S2c(WitS2cEvent::LoginCreatePlayer(LoginCreatePlayerMsg {
                character_id: 0,
            }))
        }
    }
}

/// Convert Rust S2CEvent to WIT S2CEvent
fn s2c_event_to_wit(event: &S2CEvent) -> gromnie::scripting::host::S2cEvent {
    use gromnie::scripting::host::{
        CharacterIdentity, DddInterrogationMsg, HearRangedSpeechMsg, HearSpeechMsg,
        ItemCreateObjectMsg, LoginCharacterSetMsg, LoginCreatePlayerMsg, S2cEvent as WitS2cEvent,
    };

    match event {
        S2CEvent::LoginCreatePlayer { character_id } => {
            WitS2cEvent::LoginCreatePlayer(LoginCreatePlayerMsg {
                character_id: *character_id,
            })
        }
        S2CEvent::LoginCharacterSet {
            account,
            characters,
            num_slots,
        } => WitS2cEvent::LoginCharacterSet(LoginCharacterSetMsg {
            account: account.clone(),
            characters: characters
                .iter()
                .map(|c| CharacterIdentity {
                    character_id: c.character_id.0,
                    name: c.name.clone(),
                    seconds_greyed_out: c.seconds_greyed_out,
                })
                .collect(),
            num_slots: *num_slots,
        }),
        S2CEvent::ItemCreateObject {
            object_id, name, ..
        } => WitS2cEvent::ItemCreateObject(ItemCreateObjectMsg {
            object_id: *object_id,
            name: name.clone(),
        }),
        S2CEvent::CharacterError {
            error_code,
            error_message,
        } => WitS2cEvent::CharacterError(gromnie::scripting::host::CharacterError {
            error_code: *error_code,
            error_message: error_message.clone(),
        }),
        S2CEvent::HearSpeech {
            sender_name,
            message,
            message_type,
        } => WitS2cEvent::HearSpeech(HearSpeechMsg {
            sender_name: sender_name.clone(),
            message: message.clone(),
            message_type: *message_type,
        }),
        S2CEvent::HearRangedSpeech {
            sender_name,
            message,
            message_type,
        } => WitS2cEvent::HearRangedSpeech(HearRangedSpeechMsg {
            sender_name: sender_name.clone(),
            message: message.clone(),
            message_type: *message_type,
        }),
        S2CEvent::DDDInterrogation {
            language,
            region,
            product,
        } => WitS2cEvent::DddInterrogation(DddInterrogationMsg {
            language: language.clone(),
            region: region.clone(),
            product: product.clone(),
        }),
        S2CEvent::CharGenVerificationResponse => WitS2cEvent::ChargenVerificationResponse,
        S2CEvent::MovementPositionEvent {
            object_id,
            landcell,
            x,
            y,
            z,
            quat_w,
            quat_x,
            quat_y,
            quat_z,
        } => WitS2cEvent::MovementPosition(gromnie::scripting::host::MovementPositionEventMsg {
            object_id: *object_id,
            position: gromnie::scripting::host::PositionPack {
                landcell: *landcell,
                x: *x,
                y: *y,
                z: *z,
                quat_w: *quat_w,
                quat_x: *quat_x,
                quat_y: *quat_y,
                quat_z: *quat_z,
            },
        }),
        S2CEvent::MovementPositionAndMovementEvent {
            object_id,
            landcell,
            x,
            y,
            z,
            quat_w,
            quat_x,
            quat_y,
            quat_z,
        } => WitS2cEvent::MovementPositionAndMovement(
            gromnie::scripting::host::MovementPositionAndMovementEventMsg {
                object_id: *object_id,
                position: gromnie::scripting::host::PositionPack {
                    landcell: *landcell,
                    x: *x,
                    y: *y,
                    z: *z,
                    quat_w: *quat_w,
                    quat_x: *quat_x,
                    quat_y: *quat_y,
                    quat_z: *quat_z,
                },
            },
        ),
        S2CEvent::MovementSetObjectMovement {
            object_id,
            object_instance_sequence,
        } => WitS2cEvent::MovementSetObjectMovement(
            gromnie::scripting::host::MovementSetObjectMovementMsg {
                object_id: *object_id,
                object_instance_sequence: *object_instance_sequence,
            },
        ),
        S2CEvent::EffectsPlayerTeleport {
            object_teleport_sequence,
        } => {
            WitS2cEvent::EffectsPlayerTeleport(gromnie::scripting::host::EffectsPlayerTeleportMsg {
                object_teleport_sequence: *object_teleport_sequence,
            })
        }
        // Ignore unknown S2C events (future variants added via #[non_exhaustive])
        _ => {
            warn!(target: "scripting", "Unknown S2C event variant, returning placeholder");
            WitS2cEvent::LoginCreatePlayer(LoginCreatePlayerMsg { character_id: 0 })
        }
    }
}

/// Convert Rust GameEventMsg to WIT GameEventMsg
fn game_event_msg_to_wit(event: &GameEventMsg) -> gromnie::scripting::host::GameEventMsg {
    use gromnie::scripting::host::{
        EnchantmentRemovedMsg, EnchantmentUpdatedMsg, GameEventMsg as WitGameEventMsg,
        HearDirectSpeechMsg, TradeFailureMsg, TradeItemAddedMsg, TradeItemRemovedMsg,
        TradeOpenedMsg, TradeRegisteredMsg, TransientStringMsg,
    };

    match event {
        GameEventMsg::HearDirectSpeech {
            message,
            sender_name,
            sender_id,
            target_id,
            message_type,
        } => WitGameEventMsg::HearDirectSpeech(HearDirectSpeechMsg {
            message: message.clone(),
            sender_name: sender_name.clone(),
            sender_id: *sender_id,
            target_id: *target_id,
            message_type: *message_type,
        }),
        GameEventMsg::TransientString { message } => {
            WitGameEventMsg::TransientString(TransientStringMsg {
                message: message.clone(),
            })
        }
        GameEventMsg::TradeRegistered {
            initiator_id,
            partner_id,
            stamp,
        } => WitGameEventMsg::TradeRegistered(TradeRegisteredMsg {
            initiator_id: *initiator_id,
            partner_id: *partner_id,
            stamp: *stamp,
        }),
        GameEventMsg::TradeOpened { object_id } => WitGameEventMsg::TradeOpened(TradeOpenedMsg {
            object_id: *object_id,
        }),
        GameEventMsg::TradeClosed => WitGameEventMsg::TradeClosed,
        GameEventMsg::TradeItemAdded { item_id } => {
            WitGameEventMsg::TradeItemAdded(TradeItemAddedMsg { item_id: *item_id })
        }
        GameEventMsg::TradeItemRemoved { item_id } => {
            WitGameEventMsg::TradeItemRemoved(TradeItemRemovedMsg { item_id: *item_id })
        }
        GameEventMsg::TradeAccepted => WitGameEventMsg::TradeAccepted,
        GameEventMsg::TradeDeclined => WitGameEventMsg::TradeDeclined,
        GameEventMsg::TradeReset => WitGameEventMsg::TradeReset,
        GameEventMsg::TradeFailure { reason } => {
            WitGameEventMsg::TradeFailure(TradeFailureMsg { reason: *reason })
        }
        GameEventMsg::EnchantmentUpdated {
            spell_id,
            duration,
            caster_id,
            power_level,
        } => WitGameEventMsg::EnchantmentUpdated(EnchantmentUpdatedMsg {
            spell_id: *spell_id,
            duration: *duration,
            caster_id: *caster_id,
            power_level: *power_level,
        }),
        GameEventMsg::EnchantmentRemoved { spell_id } => {
            WitGameEventMsg::EnchantmentRemoved(EnchantmentRemovedMsg {
                spell_id: *spell_id,
            })
        }
        // Ignore unknown game event messages (future variants added via #[non_exhaustive])
        _ => {
            warn!(target: "scripting", "Unknown game event message variant, returning placeholder");
            WitGameEventMsg::TransientString(TransientStringMsg {
                message: String::new(),
            })
        }
    }
}
